### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by ghost** [pbastowski/angular2-now#16]

**Comment by pbastowski** [comment]
@robertbaker Could you please elaborate on your issue?

**Comment by ghost** [comment]
@pbastowski Typescript definitions are needed for the decorators to use this in a typescript app.

**Comment by jacobdr** [comment]
@pbastowski would be the authoritative source for this, but I don't think that TypeScript definitions for angular2-now have been submitted to the [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped) repository.

However, on any page in which angular2now has been successfully loaded (or attached to the window), you can always use a `declare var angular2now;` statement in your `.ts` files to avoid compilation errors. While this of course is a workaround that costs you typechecking and the tooling benefits, it should allow you to get your code working.

I think that we should keep this issue open though as it is a very legitimate project goal, and any Typescript definitions that get submitted through a PR could be reviewed here.

**Comment by ghost** [comment]
This is what I have so far:

```
/// <reference path="../angularjs/angular.d.ts" />

declare var bootstrap: typeof angular2now.bootstrap;
declare var SetModule: typeof angular2now.SetModule;

declare module 'angular2now' {
    export var Filter: typeof angular2now.Filter;
    export var State: typeof angular2now.State;
    export var Component: typeof angular2now.Component;
    export var Service: typeof angular2now.Service;
    export var View: typeof angular2now.View;
    export var options: typeof angular2now.options;

    //export var bootstrap: typeof angular2now.bootstrap;
    //export var SetModule: typeof angular2now.SetModule;

    export var Inject: typeof angular2now.Inject;
}

declare module angular2now {
    // Class decorators.
    export function Component(config: ComponentConfig): ClassDecorator;

    export function Service(config: ServiceConfig): ClassDecorator;

    export function Filter(config: FilterConfig): ClassDecorator;

    export function State(config: StateConfig): ClassDecorator;

    export function View(config: ViewConfig): ClassDecorator;

    export function bootstrap(appName: any, dependencies?: string[]);

    export function SetModule(appName: string, dependencies?: string[]);

    export function options(config: options);

    export function Inject(dependencies: string[]);

    interface options {
        controllerAs?: string;
        spinner?: any;
        events?: any;
        noConflict?: boolean;
    }

    interface ServiceConfig {
        name: string;
    }

    interface StateConfig {
        name: string;
        url?: string;
        defaultRoute?: boolean|string;
        resolve?: any;
        controller?: ControllerClass;
        template?: any;
        html5Mode?: boolean;
    }

    interface ViewConfig {
        template?: string;
        templateUrl?: string;
    }

    interface ComponentConfig {
        selector: string;
        bind?: Bind;
        injectables?: string[];
        require?: string;
        transclude?: boolean;
    }

    interface Bind {
        [id: string]: any;
    }

    interface FilterConfig {
        name: string;
    }

    interface ControllerClass extends Function {
        template?: string|Function;
        templateUrl?: string|Function;
        link?: Function;
        compile?: any;
    }
}

```

**Comment by jacobdr** [comment]
Any chance you could submit this as a feature branch so that people can more easily pull it in for review?

**Comment by pbastowski** [comment]
Guys I'd like to help, but I'm on vacation right now without a computer.

Hovever, please have a look at this fork which uses typescript with angular2now. Perhaps it will help.

**Comment by ghost** [comment]
@pbastowski If you are talking about @nalbion's fork, that's a bit out of date. I could update it though.

@jacobdr I will once I get this working.

**Comment by pbastowski** [comment]
@robertbaker yes, I was referring to nalbion's fork. But if it's too far behind then that's no help. 

Let's collaborate on this in mid August, when I'm back from vacation.

**Comment by jjstrat3** [comment]
Any progress on this?  I'd be very interested in using angular2-now in a Typescript project I've started at my job.

**Comment by pbastowski** [comment]
No progress yet. I'm not currently using TypeScript in any of my projects, so, it has low priority.

**Comment by pbastowski** [comment]
The angular2-now NPM repo has been working with SystemJS for a while now, albeit without a .d.ts file. For a simple example see this repo: https://github.com/pbastowski/test-02.

I'm going to close this issue now, but if anyone thinks it should be reopened then please free to do so.
