### ISSUE TITLE
Attributes?

### ISSUE THREAD

**Issue by ghost** [pbastowski/angular2-now#17]
How can I declare Attributes?

Does it assume a @Component is an attribute is no @View is used?

Also for directives how can I set transclude: true or require: ngModel

**Comment by pbastowski** [comment]
1) Attributes:
`
@Component({ ..., 
  bind: { myAttr: '=' }
})
`

2) Search the README for ngmodel. There it shows you how to refer to component's controllers, including your own ngModel.

**Comment by pbastowski** [comment]
Also, bind takes the same syntax as scope with regular Angular 1 attributes.

**Comment by ghost** [comment]
I mean directives that are restrict A.

**Comment by pbastowski** [comment]
@robertbaker Sorry for the late reply, I was on vacation until yesterday, without my laptop or reasonable internet.

Both "E" and "A" type directives support transclusion. Just add a `<content></content>` block in your `template`'s HTML where you want the transcluded content to appear and transclude will be set to true automatically for you. If using `templateUrl` you'll have to add the `<div ng-transclude></div>` yourself and pass `transclude:true` into the options of `@View`

See this https://github.com/pbastowski/angular2-now#transclude-and-contentcontent section of the README for an example.

**Comment by pbastowski** [comment]
I hope the question was answered adequately. I'm closing this issue.
