### ISSUE TITLE
Is there a way to use this with angular server?

### ISSUE THREAD

**Issue by vacarsu** [pbastowski/angular2-now#21]
http://angular-meteor.com/server

I'm wanting to try out angular server in one of my apps, but it seems awkward when using angular 2 now on the client side. Is it possible to extend it to the server also?

**Comment by pbastowski** [comment]
@vacarsu Are you saying that you'd like to be able to do @Service, etc on the server side with angular-server?

**Comment by pbastowski** [comment]
For the moment I have no plans to support angular2-now on the server side, as I don't actually use angular-server myself in any of my projects.
