### ISSUE TITLE
How to get parent scope in view

### ISSUE THREAD

**Issue by rvboris** [pbastowski/angular2-now#22]
In this [example](http://plnkr.co/edit/JhHlOr?p=preview) i can not get myApp scope from a child state in views

**Comment by rvboris** [comment]
Update, i found {{$parent.myApp.test}}

**Comment by pbastowski** [comment]
@rvboris Yes, that's definitely one way to do it.

I have also updated the plunk to show how to access the parent component's controller in a child component's constructor function. See feature-two.js.
