### ISSUE TITLE
Npm package is out of date

### ISSUE THREAD

**Issue by kamilkisiela** [pbastowski/angular2-now#32]
Available versions:

> ["0.3.4","0.3.5","0.3.7","0.3.8","0.3.15","0.3.16"]

https://www.npmjs.com/package/angular2-now

**Comment by pbastowski** [comment]
Thanks. I updated it to 0.3.17, which is mostly the same as 1.0.2. However, I haven't done enough testing with @1.0.2 as an npm package to release it on npm.
