### ISSUE TITLE
Bug: cannot set specific restriction on component / directive

### ISSUE THREAD

**Issue by kamilkisiela** [pbastowski/angular2-now#35]
Line: https://github.com/pbastowski/angular2-now/blob/meteor1.2/angular2-now.js#L181

For master branch it is the 171th line.

``` javascript
{
    restrict: options.restrict || (options.template + options.templateUrl) ? 'EA' : isClass ? 'C' : 'A'
}
```

so restrict option is basically skipped all the time.

**Comment by kamilkisiela** [comment]
@pbastowski I fixed it here https://github.com/kamilkisiela/angular2-now/blob/feature/unit-tests/angular2-now.js#L181

**Comment by pbastowski** [comment]
Good pickup. It's probably been like that for a very long time. Most likely due to no one using the restrict option, but still, a very good pickup.

**Comment by kamilkisiela** [comment]
@pbastowski Do you mind if I post here each bug? So I can discuss it with you and fix it on my branch with unit testing?

I've done a lot of tests (for now it's a 58% of code coverage)

**Comment by pbastowski** [comment]
No problem, post away :)

I am not implementing the fixes on my side, because I expect you will have a PR for me when you're done.

Wow, that's excellent progress on your part re the tests.

**Comment by kamilkisiela** [comment]
@pbastowski Yes, I'm going to add PR for each bug :)

I will notify you when code coverage will be about 70%.
