### ISSUE TITLE
@State templateUrl properties doesn't work any more

### ISSUE THREAD

**Issue by hlehmann** [pbastowski/angular2-now#49]
Since the refactor, it's not possible to define a `templateUrl` in the State annotation.

I pointed the change:
https://github.com/pbastowski/angular2-now/commit/9982e46071cf8b28b66f49c0581bffd5ddb5ec53#diff-3e972fd2dbab9f5b4c0af1f0c2447076R127

``` javascript
@State({
  name: "foo",
  url: "/foo",
  controllerAs: "foo",
  templateUrl: "foo.html",
})
```

after update I get `<div ui-view>foo.html<div>` instead of the content of `foo.html`

**Comment by kamilkisiela** [comment]
We must wait for @pbastowski now, he has The Force to publish a new version :)

**Comment by hlehmann** [comment]
thx, I didn't notice those conditions.
