### ISSUE TITLE
Support for Angular 1.5

### ISSUE THREAD

**Issue by robhicks** [pbastowski/angular2-now#51]
Does angular2-now support angular 1.5 and its new components?

**Comment by kamilkisiela** [comment]
@robhicks What do you mean by that?

There are no breaking changes so angular2now should work with v1.5 (which is a RC atm).

But if you're talking about `angular.component()`.
It is basically just a wrapping function for `angular.directive()`.

Here is a commit with this new feature https://github.com/angular/angular.js/commit/54e816552f20e198e14f849cdb2379fed8570c1a

So I think you can easily use just [`@Component`](https://github.com/pbastowski/angular2-now/blob/master/src/api/component.js#L102-L114) decorator.

**Comment by robhicks** [comment]
@kamilkisiela Thanks that's what I needed to know.
